id = "flint"
name = "Flint"
version = "0.1.0"
description = "Support for the Flint Programming Language"
schema_version = 1
authors = ["Julius Gr√ºnberg <ghastcrafthd@troense.de>"]
repository = "https://github.com/GhastCraftHD/flint-zed"

[grammars.flint]
repository = "https://github.com/flint-lang/tree-sitter-flint"
commit = "6b862569ec45646160e8e261896521dc48da3b89"
